Implement AWS authentication method
buildkite-plugins/vault-secrets-buildkite-plugin pull request #15
Opened 2022-12-22 14:40 UTC by fd-jonathanlinn

- Adds support for the [AWS auth method](https://developer.hashicorp.com/vault/docs/auth/aws) in Vault
- This method will look for a parameter `aws-role-name` from the plugin configuration; if undefined, it will try to use the name of the IAM role attached to the EC2 instance (only if running on EC2)
- Updates README with table of configuration options and example of using aws auth method

<img width="715" alt="Screenshot 2022-12-22 at 14 32 26" src="https://user-images.githubusercontent.com/62928797/209157650-170c4de4-d64f-4b7a-9312-56beea6759e8.png">

> _The "unable to list secrets" is due to there being no secret with the pipeline-slug in its name, not because of anything functional._

Approle authentication wasn't suitable for our particular use case so I've implemented the AWS auth method here.  This works as expected on our end; there's no functional change to how secrets are retrieved, only the initial authentication method.  I also took a swing at the README to try and make it a bit more readable.

If/when another authentication method is added we might want to change to a `case` for the method check, but for 2 methods I think this is okay for now.

2023-01-05 12:05 UTC, fd-jonathanlinn commented
@jeremybumsted @pzeballos happy new year!  Tagging yourselves to hopefully get this reviewed as you're the 2 most recent contributors to the repo, please let me know if this isn't correct (no contributing guide in the readme 😓)

2023-01-05 15:39 UTC, jeremybumsted commented
Hey @fd-jonathanlinn Happy New Year! Thanks for tagging - We'll give this a review shortly here 😄.

2023-01-17 13:59 UTC, fd-jonathanlinn commented
> Hey @fd-jonathanlinn Happy New Year! Thanks for tagging - We'll give this a review shortly here 😄.

Do you know when that's likely to be?  Apologies if I'm coming off as pushy, I'm just keen to start relying on the official version of this rather than the fork for things we're building out 😅

2023-01-24 23:47 UTC, jeremybumsted requested changes
@fd-jonathanlinn Awesome stuff! 🙌  Sorry that it took so long to get to this! 

I'd only ask for some tests to verify this auth method works here. 

I don't think integration tests are needed for now, but you can see an example of the updated tests for `approle` auth [here](https://github.com/buildkite-plugins/vault-secrets-buildkite-plugin/pull/13/commits/51d84723bb1286937b812fdfd2c856797af352a0)

2023-01-27 14:26 UTC, fd-jonathanlinn commented
Hey @jeremybumsted I can try but I'm not sure I can do so effectively since those changes are still in progress/have pending changes.  Presumably you'd want the test added to your fork's branch as opposed to here since it'll be a pain to resolve the merge conflicts?  Let me know how you'd like to proceed and I'll do my best 😄

2023-06-29 21:35 UTC, jeremybumsted commented
This should be added in #24 and available in the latest release :)

2023-06-29 21:35 UTC, closed without merging