Tester and cleanup
buildkite-plugins/vault-secrets-buildkite-plugin pull request #22
Opened 2023-04-10 05:17 UTC by toote

* deactivated the dependency dashboard (closes #6)
* uses plugin tester instead of docker compose in pipeline
* refactor and clean-up in tests
  - `unset` calls are no longer necessary
  - moved common variables to all tests to `setup` function
  - use tester variable to load extensions
  - fixed all test data format (should have been YAML-like)
* shellcheck warnings and errors
  - corrected them all in all scripts in repository
  - added all scripts in repository to shellcheck plugin paths
* big fixes in `git-credential-vault-secrets`
  - output now includes port in the `host` entry (as [per spec](https://git-scm.com/docs/git-credential#Documentation/git-credential.txt-codehostcode))
  - when parsing finishes, function does not fail (which prevented tests with arguments)
* added a lot of tests to `git-credential-vault-secrets`

2023-04-20 18:59 UTC, jeremybumsted requested changes
@toote amazing stuff, added some comments with suggestions, but everything else makes sense and looks good to me 💪

2023-04-20 18:59 UTC, jeremybumsted commented on examples/update-sshkey-secret
> +  base64 "${TMPDIR}/private_ssh_key.pub" \
Same thing here, no need to base64 encode the secret since it's no longer required to process the secrets

2023-04-20 18:59 UTC, jeremybumsted commented on examples/update-sshkey-secret
> +  base64 "${TMPDIR}/private_ssh_key" \
Same thing here, no need to base64 encode the secret since it's no longer required to process the secrets

2023-04-20 18:59 UTC, jeremybumsted commented on .buildkite/pipeline.yml
> +      - tester#v1.0.0: ~
Update plugin name:

```suggestion
      - plugin-tester#v1.0.0: ~
```

2023-04-20 20:34 UTC, toote commented on .buildkite/pipeline.yml
> +      - tester#v1.0.0: ~
duh 🤦

2023-04-20 20:35 UTC, toote commented on examples/update-env-secret
> +echo -n "$(echo "${var}='${_val}'" | base64)" | vault write "${BASE_PATH}${PIPELINE}/env/${var}" value=-
In that case the internal echo is not necessary and could be something like:

```suggestion
echo -n "${var}='${_val}'" | vault write "${BASE_PATH}${PIPELINE}/env/${var}" value=-
```

Right?

2023-04-20 20:37 UTC, toote commented on examples/update-env-secret
> +echo -n "$(echo "${var}='${_val}'" | base64)" | vault write "${BASE_PATH}${PIPELINE}/env/${var}" value=-
Better yet, there is no need for an `echo` at all:
```suggestion
vault write "${BASE_PATH}${PIPELINE}/env/${var}" value="${var}='${_val}'"
```

Or am I missing anything?

2023-04-20 20:39 UTC, jeremybumsted commented on examples/update-env-secret
> +echo -n "$(echo "${var}='${_val}'" | base64)" | vault write "${BASE_PATH}${PIPELINE}/env/${var}" value=-
Oh yeah, nice catch. You wouldn't need the echo at all.

2023-04-20 20:51 UTC, toote commented on examples/update-sshkey-secret
> +  | vault write "${BASE_PATH}${PIPELINE}/private_ssh_key" value=-
```suggestion
  cat "${TMPDIR}/private_ssh_key" \
  | vault write "${BASE_PATH}${PIPELINE}/private_ssh_key" value=-
```

2023-04-20 20:52 UTC, toote commented on examples/update-sshkey-secret
> +  | vault write "${BASE_PATH}${PIPELINE}/private_ssh_key.pub" value=-
```suggestion
  cat "${TMPDIR}/private_ssh_key.pub" \
  | vault write "${BASE_PATH}${PIPELINE}/private_ssh_key.pub" value=-
```

2023-04-21 16:32 UTC, jeremybumsted approved these changes
Looks good to me!

2023-04-24 22:21 UTC, merged